/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Windows;

import Utils.Conex;
import Utils.Crud_AgregarProfesor;
import Utils.crud_editarProfesor;
import Utils.crud_profesores;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thexe
 */
public class Profesores extends javax.swing.JPanel {

    crud_profesores profesores = new crud_profesores();
    Crud_AgregarProfesor ps = new Crud_AgregarProfesor();
    crud_editarProfesor ep = new crud_editarProfesor();

    DefaultTableModel tablaModelo = new DefaultTableModel(new Object[]{"Identificador", "Cedula", "Nombre", "Apellido"}, 0);
    String nombre = "";
    int idpro = 0;

    /**
     * Creates new form Profesores
     */
    public Profesores() {
        initComponents();
        jTable1.setModel(tablaModelo);
        profesores.cargarTabla(jTable1);
        jtxtIdentificador.setEnabled(false);
        profesores.actualizarLabelIdentificador(jtxtIdentificador);

        jtxtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtNombreFocusLost(evt);
            }
        });

    }

    private void jtxtNombreFocusLost(java.awt.event.FocusEvent evt) {
        // Recuperar el texto del JTextField cuando pierde el foco
        nombre = jtxtNombre.getText();
        System.out.println(nombre);

    }

    private void mostrarDatosSeleccionados() {
        int filaSeleccionada = jTable1.getSelectedRow();

        if (filaSeleccionada >= 0) {
            String identificador = jTable1.getValueAt(filaSeleccionada, 0).toString();
            String cedula = (String) jTable1.getValueAt(filaSeleccionada, 1);
            String nombre = (String) jTable1.getValueAt(filaSeleccionada, 2);
            String apellido = (String) jTable1.getValueAt(filaSeleccionada, 3);

            // Mostrar los datos en los componentes correspondientes
            pnlCrearProfesor.setEnabled(false);
            jtxtNombre.setText(nombre);
            jtxtCedula.setText(cedula);
            jtxtApellido.setText(apellido);
            jtxtIdentificador.setText(identificador);

        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtCedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtIdentificador = new javax.swing.JTextField();
        pnlEliminarProfesor = new Utils.PanelShadow();
        jLabel3 = new javax.swing.JLabel();
        pnlEditarProfesor = new Utils.PanelShadow();
        jLabel4 = new javax.swing.JLabel();
        pnlCrearProfesor = new Utils.PanelShadow();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("PROFESORES");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));
        add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 142, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Apellido:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 580, 320));
        add(jtxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 177, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Cedula:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));
        add(jtxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 107, 150, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Identificador:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));
        add(jtxtIdentificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 100, -1));

        pnlEliminarProfesor.setBackground(new java.awt.Color(173, 39, 46));
        pnlEliminarProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEliminarProfesorMouseClicked(evt);
            }
        });
        pnlEliminarProfesor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ELIMINAR");
        pnlEliminarProfesor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        add(pnlEliminarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 160, 50));

        pnlEditarProfesor.setBackground(new java.awt.Color(173, 39, 46));
        pnlEditarProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEditarProfesorMouseClicked(evt);
            }
        });
        pnlEditarProfesor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EDITAR");
        pnlEditarProfesor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        add(pnlEditarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 160, 50));

        pnlCrearProfesor.setBackground(new java.awt.Color(173, 39, 46));
        pnlCrearProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCrearProfesorMouseClicked(evt);
            }
        });
        pnlCrearProfesor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CREAR");
        pnlCrearProfesor.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        add(pnlCrearProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 150, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        mostrarDatosSeleccionados();
    }//GEN-LAST:event_jTable1MouseClicked

    private void pnlCrearProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCrearProfesorMouseClicked
        if (profesores.ComprobarCedula2(jtxtCedula.getText())) {
            profesores.addProfesor(jtxtIdentificador.getText(), jtxtCedula.getText(), jtxtNombre.getText(), jtxtApellido.getText(), jTable1);
            profesores.actualizarLabelIdentificador(jtxtIdentificador);
            jtxtCedula.setText("");
            jtxtNombre.setText("");
            jtxtApellido.setText("");
        } else {
            return;
        }
    }//GEN-LAST:event_pnlCrearProfesorMouseClicked

    private void pnlEditarProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditarProfesorMouseClicked
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada != -1) {
            if (profesores.ComprobarCedula2(jtxtCedula.getText())) {
                profesores.editarProfesor(jtxtIdentificador.getText(), jtxtCedula.getText(), jtxtNombre.getText(), jtxtApellido.getText(), jTable1);
                profesores.actualizarLabelIdentificador(jtxtIdentificador);
                jtxtCedula.setText("");
                jtxtNombre.setText("");
                jtxtApellido.setText("");
                pnlCrearProfesor.setEnabled(true);
            } else {
                return;
            }

        } else {
            System.out.println("Por favor, seleccione un profesor para editar.");
        }


    }//GEN-LAST:event_pnlEditarProfesorMouseClicked

    private void pnlEliminarProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEliminarProfesorMouseClicked
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada != -1) {
            profesores.eliminarProfesor(jtxtIdentificador.getText(), jTable1);
            profesores.actualizarLabelIdentificador(jtxtIdentificador);
            jtxtCedula.setText("");
            jtxtNombre.setText("");
            jtxtApellido.setText("");
            pnlCrearProfesor.setEnabled(true);
        } else {
            System.out.println("Por favor, seleccione un profesor para eliminar.");
        }
    }//GEN-LAST:event_pnlEliminarProfesorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtApellido;
    private javax.swing.JTextField jtxtCedula;
    private javax.swing.JTextField jtxtIdentificador;
    private javax.swing.JTextField jtxtNombre;
    private Utils.PanelShadow pnlCrearProfesor;
    private Utils.PanelShadow pnlEditarProfesor;
    private Utils.PanelShadow pnlEliminarProfesor;
    // End of variables declaration//GEN-END:variables
}
